# Configuration file for GoReleaser - https://goreleaser.com/build/
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64

archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - none*

snapcraft:
  name_template: "qlik-{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
  name: qlik-corectl

  publish: true

  summary: A command line interface tool for the Qlik Associative Engine
  description: |
    Qlik Core Control (corectl) is a tool that delivers a
    command line interface (CLI) for the Qlik Associative Engine.
    With corectl you can interact with your apps, objects, and data.
  grade: stable
  confinement: strict

  apps:
    corectl:
      plugs: ["home", "network"]
