version: 2
jobs:
  build:
    working_directory: ~/corectl
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "go.sum" }}
      - run:
          name: Build
          command: go build -ldflags "-X main.version=$(git describe --tag --abbrev=0)"
      - save_cache:
          key: dependency-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Linting
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status
      - run:
          name: Test
          command: go test -v -race ./...
      - run:
          name: Check if documentation needs to be updated
          command: |
            ./corectl generate-docs
            git diff --exit-code --name-only docs/*.md
      - run:
          name: Check if changes has been done to the CLI API
          command: |
            ./corectl generate-spec > ./docs/spec.json
            git diff --exit-code --name-only docs/spec.json
      - store_artifacts:
          path: ./docs/spec.json
      - setup_remote_docker
      - run:
          name: Run Integration Test
          command: |
            # Spin up environment
            ACCEPT_EULA=yes docker-compose -f ./test/docker-compose.yml up -d
            ENGINE_STD_CONTAINER_ID=$(docker ps -aqf "name=engine-std")
            ENGINE_ABAC_CONTAINER_ID=$(docker ps -aqf "name=engine-abac")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$ENGINE_STD_CONTAINER_ID")
            # Start a container for test execution
            TEST_CONTAINER=$(docker run -e TEST_HOST=$TEST_HOST -d golang:1.12-alpine tail -f /dev/null)
            # Install packages
            docker exec $TEST_CONTAINER sh -c 'apk update && apk add --no-cache bash gcc git libc-dev'
            # Copy code into container
            docker cp /go/pkg $TEST_CONTAINER:/go/pkg
            docker cp . $TEST_CONTAINER:/corectl
            # Copy apps and data into the first engine container, the second one does not need it. Third engine container needs the data and the rules.
            chmod -R 777 ./test/
            docker cp ./test/apps/ $ENGINE_STD_CONTAINER_ID:/
            docker cp ./test/data/ $ENGINE_STD_CONTAINER_ID:/
            docker cp ./test/data/ $ENGINE_ABAC_CONTAINER_ID:/
            docker cp ./test/rules/ $ENGINE_ABAC_CONTAINER_ID:/
            # Execute tests
            docker exec $TEST_CONTAINER /bin/bash -c 'cd /corectl && go test ./test/corectl_integration_test.go --engineStd $TEST_HOST:9076 --engineJwt $TEST_HOST:9176 --engineAbac $TEST_HOST:9276 --engineBadLicenseServer $TEST_HOST:9376 '

  validate:
    working_directory: ~/corectl
    docker:
      - image: circleci/node:8.16.0
    steps:
      - checkout
      - run:
          name: Install aws-cli
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Download api schema
          command: aws s3 cp s3://${S3BUCKET}/schema.json ./docs/schema.json --region ${S3BUCKET_REGION}
      - run:
          name: Install ajv-cli
          command: sudo npm install -g ajv-cli
      - run:
          name: Validate api spec towards schema
          command: ajv -s ./docs/schema.json -d ./docs/spec.json --json-pointers=true --all-errors=true

  copy_go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - persist_to_workspace:
        root: /
        paths:
          - go
          - usr/local/go

  test_publish:
    working_directory: ~/corectl
    docker:
      - image: cibuilds/snapcraft
        #- image: snapcore/snapcraft
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: copy go
          command: |
            sudo mv /tmp/workspace/go /go
            sudo mv /tmp/workspace/usr/local/go /usr/local/go
            export PATH="/go/bin:/usr/local/go/bin:$PATH"
      - run:
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            #sudo apt update && sudo apt install -y curl
      - run: curl -sL https://git.io/goreleaser | bash -s -- --skip-publish --skip-validate

  publish:
    working_directory: ~/corectl
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /v.*/
      - validate:
          filters:
            tags:
              only:
                - /v.*/
      - copy_go:
          filters:
            tags:
              only:
                - /v.*/
      - test_publish:
          requires:
            - copy_go
          filters:
            tags:
              only:
                - /v.*/
      - publish:
          requires:
            - build
            - validate
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/
