version: 2
jobs:
  build:
    working_directory: ~/corectl
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "go.sum" }}
      - run:
          name: Build
          command: go build -ldflags "-X main.version=$(git describe --abbrev=0 --tags)"
      - save_cache:
          key: dependency-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Linting
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status
      - run:
          name: Test
          command: go test -v -race ./...
      - run:
          name: Check if documentation needs to be updated
          command: |
            ./corectl generate-docs
            git diff --exit-code --name-only docs/*.md
      - run:
          name: Check if changes has been done to the CLI API
          command: |
            ./corectl generate-spec > ./docs/spec.json
            git diff --exit-code --name-only docs/spec.json
      - store_artifacts:
          path: ./docs/spec.json
      - setup_remote_docker
      - run:
          name: Run Integration Test
          command: |
            # Spin up environment
            ACCEPT_EULA=yes docker-compose -f ./test/docker-compose.yml up -d
            ENGINE_1_CONTAINER_ID=$(docker ps -aqf "name=engine-1")
            ENGINE_3_CONTAINER_ID=$(docker ps -aqf "name=engine-3")
            TEST_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' "$ENGINE_1_CONTAINER_ID")
            # Start a container for test execution
            TEST_CONTAINER=$(docker run -e TEST_HOST=$TEST_HOST -d golang:1.12-alpine tail -f /dev/null)
            # Install packages
            docker exec $TEST_CONTAINER sh -c 'apk update && apk add --no-cache bash gcc git libc-dev'
            # Copy code into container
            docker cp /go/pkg $TEST_CONTAINER:/go/pkg
            docker cp . $TEST_CONTAINER:/corectl
            # Copy apps and data into the first engine container, the second one does not need it. Third engine container needs the data and the rules.
            chmod -R 777 ./test/
            docker cp ./test/apps/ $ENGINE_1_CONTAINER_ID:/
            docker cp ./test/data/ $ENGINE_1_CONTAINER_ID:/
            docker cp ./test/data/ $ENGINE_3_CONTAINER_ID:/
            docker cp ./test/rules/ $ENGINE_3_CONTAINER_ID:/
            # Execute tests
            docker exec $TEST_CONTAINER /bin/bash -c 'cd /corectl && go test ./test/corectl_integration_test.go --engineIP $TEST_HOST:9076 --engine2IP $TEST_HOST:9176 --engine3IP $TEST_HOST:9276'

  publish:
    working_directory: ~/corectl
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /v.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/
